corrected user creation problems

diff --git a/.devcontainer/texlive/Dockerfile b/.devcontainer/texlive/Dockerfile
--- a/.devcontainer/texlive/Dockerfile
+++ b/.devcontainer/texlive/Dockerfile
@@ -11,32 +11,37 @@ RUN apt-get update && apt-get install -y \
     curl \
     wget \
     fonts-powerline \
+    sudo \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/*
 
-# Create a non-root user matching host user
+# Create a non-root user with sudo access - SIMPLIFIED VERSION
+# Update just the user creation section
 ARG USERNAME=vscode
 ARG USER_UID=1000
-ARG USER_GID=$USER_UID
+ARG USER_GID=1000
 
-RUN groupadd --gid $USER_GID $USERNAME \
-    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
-    && apt-get update \
-    && apt-get install -y sudo \
-    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
-    && chmod 0440 /etc/sudoers.d/$USERNAME
+# Fix typo in id command and improve error handling
+RUN groupadd -g $USER_GID -o $USERNAME 2>/dev/null || echo "Group exists" && \
+    useradd -u $USER_UID -g $USER_GID -s /bin/bash -m $USERNAME 2>/dev/null || \
+    useradd -g $USER_GID -s /bin/bash -m $USERNAME 2>/dev/null || echo "User exists" && \
+    echo "$USERNAME ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME && \
+    chmod 0440 /etc/sudoers.d/$USERNAME && \
+    id $USERNAME || echo "Warning: User verification failed"
 
 # Create directories if they don't exist
 RUN mkdir -p /etc/zsh/zshrc.d
 
-# Set up Oh My Zsh
-RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended \
-    && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions \
-    && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
+# Set up Oh My Zsh for root
+RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
 
-# Configure Oh My Zsh with plugins
-RUN sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="agnoster"/' ~/.zshrc \
-    && sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/' ~/.zshrc
+# Configure zsh for the user
+RUN mkdir -p /home/$USERNAME/.oh-my-zsh && \
+    cp -r /root/.oh-my-zsh/* /home/$USERNAME/.oh-my-zsh/ && \
+    cp /root/.zshrc /home/$USERNAME/.zshrc && \
+    sed -i 's/\/root\/.oh-my-zsh/\/home\/'"$USERNAME"'\/.oh-my-zsh/g' /home/$USERNAME/.zshrc && \
+    chown -R $USERNAME:$USERNAME /home/$USERNAME/.oh-my-zsh && \
+    chown $USERNAME:$USERNAME /home/$USERNAME/.zshrc
 
 # Create auto-completion setup
 RUN echo 'autoload -Uz compinit && compinit\n\
@@ -59,11 +64,8 @@ alias latexmk="latexmk -pdf -interaction=nonstopmode"\n\
 ' > /etc/zsh/zshrc.d/custom-setup.zsh
 
 # Update .zshrc to source custom scripts
-RUN echo 'source /etc/zsh/zshrc.d/custom-setup.zsh' >> ~/.zshrc \
-    && echo 'source /etc/zsh/zshrc.d/auto-completion.zsh' >> ~/.zshrc
-
-# Set up Oh My Zsh for the user
-RUN su $USERNAME -c 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended'
+RUN echo 'source /etc/zsh/zshrc.d/custom-setup.zsh' >> /home/$USERNAME/.zshrc \
+    && echo 'source /etc/zsh/zshrc.d/auto-completion.zsh' >> /home/$USERNAME/.zshrc
 
 # Set working directory
 WORKDIR /workspace/texlive-workspace
